### ISSUE TITLE
Cannot build from source for C++ operations

### ISSUE THREAD

**Issue by cfgfung** [alibaba/graphlearn-for-pytorch#18]
### 🐛 Describe the bug

Hi,

I followed the guide and tried to build the code from the source. I am using GCC 10.4.0 and the exact version of GoogleTest branch (through 'git submodule update --init')

Here is the error message:
'[ 76%] Built target test_vineyard
/usr/bin/ld: CMakeFiles/test_shm_queue.dir/test/cpp/test_shm_queue.cu.o: in function `testing::AssertionResult testing::internal::CmpHelperOpFailure<int, int>(char const*, char const*, int const&, int const&, char const*)':
tmpxft_000058eb_00000000-6_test_shm_queue.cudafe1.cpp:(.text._ZN7testing8internal18CmpHelperOpFailureIiiEENS_15AssertionResultEPKcS4_RKT_RKT0_S4_[_ZN7testing8internal18CmpHelperOpFailureIiiEENS_15AssertionResultEPKcS4_RKT_RKT0_S4_]+0x90): undefined reference to `testing::Message::GetString() const'
'

### Environment

* GLT version: Latest main branch
* PyG version: 2.3
* PyTorch version: 2.0.0 + cu11.7
* OS: ubuntu 22.04 LTS
* Python version: 3.9.16
* CUDA/cuDNN version: --- Driver Version: 530.30.02 , CUDA Version: 12.1
* Any other relevant information

**Comment by baoleai** [comment]
Did you run "bash install_dependencies.sh" before cmake?

**Comment by cfgfung** [comment]
Did something similar. I ran 'bash build.sh' to build the googletest instead.

**Comment by baoleai** [comment]
It seems like you are having a link error about GTest, are there multiple Gtest installed in your env? You can check the CMakeFiles for the link and include info.

**Comment by cfgfung** [comment]
Yes, the problem is due to the multiple GTest. 
It is also found that we have to use < 1.10 version GCC/G++ to build the third-party GoogleTest. A warning, which will then cause the building of GTest to fail, will happen.
Details: https://stackoverflow.com/questions/69935158/dummy-may-be-used-uninitialized

**Comment by baoleai** [comment]
It seems like GTest branch v1.12.x has fixed this warning. If so,  you can update GTest submodule to v1.12.x
