### ISSUE TITLE
Add supports for weighted edge sampling

### ISSUE THREAD

**Issue by vincentX3** [alibaba/graphlearn-for-pytorch#69]
### 🚀 The feature, motivation and pitch

In large graphs with more than ten million edges, the need for edge sampling is inevitable. Hopefully, GLT can support sampling based on edge weights, so as to better utilize edge features.

Related Content: 
PyG
- https://github.com/rusty1s/pytorch_cluster/pull/140

DGL：node2vec random walk and top-k sampling
- https://docs.dgl.ai/en/0.8.x/api/python/dgl.sampling.html#neighbor-sampling

**Comment by LiSu** [comment]
Same with #68, closed.
